
version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      # - restore_cache:
      #     key: deps9-{{ .Branch }}-{{ checksum "environment.yml" }}
      - run:
          name: Install dependencies
          command: conda env create -f environment.yml
      # - run:
      #     name: "Update conda"
      #     command: conda env update -f environment.yml
      # - run:
      #     command: |
      #       conda env list | grep anaconda-docker >/dev/null
      #       if [[ $? != 0 ]]; then
      #           conda env create -f environment.yml
      #       fi
      # - save_cache:
      #     key: deps9-{{ .Branch }}-{{ checksum "environment.yml" }}
      #     paths:
      #       - "/opt/conda"
      - run:
          name: Run unit tests
          command: conda run -n anaconda-docker python -m unittest discover -v
      - run:
          name: Remove environment
          command: conda remove --name anaconda-docker --all --yes
