version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:

  build-osquery:
    executor:
      name: win/default
    steps: 
      - checkout
      - run: 
          name: "Install osquery w choco"
          shell: powershell.exe # default shell is Powershell
          command: choco install osquery --params='/InstallService'
      - run: 
          name: "Start osquery service"
          shell: powershell.exe # default shell is Powershell
          command: Start-service osqueryd        
      - run: 
          name: "Query osquery service"
          shell: powershell.exe # default shell is Powershell
          command: Get-Service | Where-Object {$_.name -eq “osqueryd”}       

workflows:
  commit-parallel-workflow:
    jobs:
      - build-osquery
  scheduled-workflow:
    triggers:
      - schedule:        
          cron: "0,15,30,45 * * * *" # at minutes 0, 15, 30, 45
          # cron: "0 0 1 * *" # once a month
          filters:
            branches:
              only: 
              - master
    jobs:
      - build-osquery