
version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:

  build-choco-osquery:
    executor: 
      name: win/default
    steps: 
      - checkout
      - run: choco install osquery --params='/InstallService'
      - run: Start-service osqueryd
      - run: Get-Service | Where-Object {$_.name -eq “osqueryd”}
      # - run: choco install vagrant #Packages requiring reboot:
      # - run: vagrant version

  build-scoop:
    executor: 
      name: win/default
    steps: 
      - checkout
      - run:
          name: "helloworld powershell"            
          command: $(echo hello | Out-Host; $?) -and $(echo world | Out-Host; $?)
          shell: powershell.exe # default shell is Powershell      
      - run:
          name: "change the execution policy (i.e. enable Powershell) "            
          command: "Set-ExecutionPolicy RemoteSigned -scope CurrentUser"
          shell: powershell.exe # default shell is Powershell           
      - run:
          name: "Install scoop" 
          command: "Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')"
          # Make sure PowerShell 5 (or later, include PowerShell Core) and .NET Framework 4.5 (or later) are installed           
          shell: powershell.exe # default shell is Powershell
      - run:
          name: "scoop help "            
          command: "scoop help"
          shell: powershell.exe # default shell is Powershell

  build-scoop-shorter:
    executor: 
      name: win/default
    steps: 
      - checkout
      - run:
          name: "helloworld powershell"            
          command: $(echo hello | Out-Host; $?) -and $(echo world | Out-Host; $?)
          shell: powershell.exe # default shell is Powershell      
      - run:
          name: "change the execution policy (i.e. enable Powershell) "            
          command: "Set-ExecutionPolicy RemoteSigned -scope CurrentUser"
          shell: powershell.exe # default shell is Powershell           
      - run:
          name: "Install scoop - shorter" 
          command: "iwr -useb get.scoop.sh | iex"
          # Make sure PowerShell 5 (or later, include PowerShell Core) and .NET Framework 4.5 (or later) are installed           
          shell: powershell.exe # default shell is Powershell
      - run:
          name: "scoop help "            
          command: "scoop help"
          shell: powershell.exe # default shell is Powershell                                    
      # - run: 
      #     name: "Install scoop"
      #     shell: powershell.exe # default shell is Powershell
      #     # iwr : Win32 internal error "Access is denied" 0x5 
      #     command: | 
      #       iwr -useb get.scoop.sh | iex # or shorter #The command "iwr -useb get.scoop.sh | iex" exited with 127.
      #       scoop install vagrant
      #       vagrant version      

  build-multi-shells:
    executor: 
      name: win/default
    steps: 
      - checkout
      - run:
          name: "helloworld in powershell"            
          command: $(echo hello | Out-Host; $?) -and $(echo world | Out-Host; $?)
          shell: powershell.exe # default shell is Powershell  
      - run:
          name: "helloworld in bash"            
          command: echo hello && echo world
          shell: bash.exe
      - run:
          name: "helloworld in cmd"            
          command: echo hello & echo world
          shell: cmd.exe

workflows:
  commit-parallel-workflow:
    jobs:
      - build-choco-osquery
      - build-scoop
      - build-scoop-shorter
      - build-multi-shells